spring:
  profiles:
    active:
  datasource:
      url: jdbc:postgresql://localhost:5432/news
      password: 1234
      username: roman
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      news-live-time: 100
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 4
