spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/news
      password: 1234
      username: roman
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234