spring:
  profiles:
    active:
  datasource:
      url: jdbc:postgresql://${DATABASE_NAME}:5432/news
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      news-live-time: ${SPRING_DATA_REDIS_NEWS_LIVE_TIME:100}
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 4
