version: "3.9"

networks:
  app-tier:
    driver: "bridge"

services:
  db:
    image: "postgres:16.3"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=roman"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=news"
    networks:
      - app-tier


  redis:
    image: "redis:7.4.0"
    restart: "always"
    container_name: "redis_db"
    ports:
      - "6379:6379"
    networks:
      - app-tier
    depends_on:
      - db


